### ISSUE TITLE
Empty Json File

### ISSUE THREAD

**Issue by ZachRN** [nickgerrets/JsonParser#2]
```
JsonParser parser(argv[1]);
Json::pointer json = parser.parse();
```
In the above snippet when passing an empty json file to parser, it will then hang in the parser.parse() function for an indefinite amount of time.

**Comment by nickgerrets** [comment]
Resolved through commit [205011e](https://github.com/nickgerrets/njson/commit/205011e7fddb39c86230b7c9d6356431d4268477)
